
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.6
 * Tue Aug 25 20:25:45 ART 2020
 * Generated source version: 3.3.6
 */

@XmlRootElement(name = "getNoticiasResponse", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNoticiasResponse", namespace = "http://ws.das.ubp.edu.ar/")

public class GetNoticiasResponse {

    @XmlElement(name = "return")
    private ar.edu.ubp.das.bean.ws.NoticiaResponseBean _return;

    public ar.edu.ubp.das.bean.ws.NoticiaResponseBean getReturn() {
        return this._return;
    }

    public void setReturn(ar.edu.ubp.das.bean.ws.NoticiaResponseBean new_return)  {
        this._return = new_return;
    }

}

