
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.6
 * Sun Aug 23 16:18:28 ART 2020
 * Generated source version: 3.3.6
 */

@XmlRootElement(name = "getToken", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getToken", namespace = "http://ws.das.ubp.edu.ar/")

public class GetToken {

    @XmlElement(name = "arg0")
    private ar.edu.ubp.das.bean.TokenRequestBean arg0;

    public ar.edu.ubp.das.bean.TokenRequestBean getArg0() {
        return this.arg0;
    }

    public void setArg0(ar.edu.ubp.das.bean.TokenRequestBean newArg0)  {
        this.arg0 = newArg0;
    }

}

