
package ar.edu.ubp.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2022-06-11T19:06:52.516-03:00
 * Generated source version: 3.3.6
 *
 */

public class GenerarToken_PortTypeServer{

    protected GenerarToken_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.ws.GenerarToken();
        String address = "http://localhost:9090/TokenPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new GenerarToken_PortTypeServer();
        System.out.println("Server ready...");

        System.out.println("Server exiting");
        System.exit(0);
    }
}

